In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from imblearn.over_sampling import SMOTE

In [2]:
df=pd.read_csv('Frogs_MFCCs.csv')

__data split__

In [3]:
msk=np.random.rand(len(df))<0.7
train=df[msk]
test=df[~msk]

__(b)ii SVM__

In [4]:
svc = SVC(C=8,kernel='rbf',gamma=0.01)
#svc.fit(train.iloc[:,:22],train.iloc[:,23])
#set(svc.predict(test.iloc[:,:22]))

In [5]:
parameters={'C':[4,6,8,10],'gamma':[0.1,0.5,1]}
clf=GridSearchCV(svc,param_grid=parameters,cv=10)
clf.fit(np.array(train.iloc[:,:22]),np.array(train.iloc[:,23]))
accuracy_score(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

0.9907961343764381

In [6]:
confusion_matrix(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

array([[1238,    0,    1,    4,    0,    0,    0,    0],
       [   0,  165,    1,    0,    0,    0,    0,    0],
       [   4,    0,   84,    0,    0,    0,    0,    0],
       [   1,    0,    0,  483,    1,    0,    0,    0],
       [   0,    0,    0,    4,   88,    0,    0,    0],
       [   0,    0,    0,    1,    0,   36,    0,    0],
       [   0,    0,    0,    0,    0,    0,   19,    0],
       [   1,    0,    1,    0,    0,    1,    0,   40]], dtype=int64)

In [7]:
parameters={'C':[4,6,8,10],'gamma':[0.1,0.5,1]}
clf=GridSearchCV(svc,param_grid=parameters,cv=10)
clf.fit(train.iloc[:,:22],train.iloc[:,24])
accuracy_score(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

0.9894155545329039

In [8]:
confusion_matrix(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

array([[ 181,    0,    0,    1,    2,    1,    0,    0,    0,    0],
       [   0, 1057,    0,    0,    0,    1,    0,    0,    0,    0],
       [   0,    0,  165,    1,    0,    0,    0,    0,    0,    0],
       [   2,    3,    2,   81,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  145,    0,    0,    0,    0,    0],
       [   0,    1,    0,    0,    2,  337,    0,    0,    0,    0],
       [   0,    0,    0,    0,    2,    1,   88,    0,    1,    0],
       [   0,    0,    0,    0,    0,    0,    0,   37,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   19,    0],
       [   1,    0,    0,    1,    0,    0,    0,    0,    1,   40]],
      dtype=int64)

In [10]:
parameters={'C':[4,6,8,10],'gamma':[0.1,0.5,1]}
clf=GridSearchCV(svc,param_grid=parameters,cv=10)
clf.fit(train.iloc[:,:22],train.iloc[:,25])
accuracy_score(test.iloc[:,25],clf.predict(test.iloc[:,:22]))

C:\Users\li chen\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.8881730326737229

In [11]:
confusion_matrix(test.iloc[:,25],clf.predict(test.iloc[:,:22]))

array([[16,  0,  0, ...,  0,  0,  0],
       [ 1, 14,  0, ...,  0,  0,  0],
       [ 0,  0,  4, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 10,  0,  0],
       [ 0,  0,  0, ...,  0,  7,  0],
       [ 0,  0,  0, ...,  0,  0,  5]], dtype=int64)

__(b)iii L1-penalized SVMs__

In [12]:
for i in df.iloc[:,:22]:
    df[i]=(df[i]-min(df[i]))/(max(df[i])-min(df[i]))
msk=np.random.rand(len(df))<0.7
train=df[msk]
test=df[~msk]

In [13]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,6,8,10]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(train.iloc[:,:22],train.iloc[:,23])


GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [4, 6, 8, 10]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [14]:
accuracy_score(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

0.9500950570342205

In [15]:
confusion_matrix(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

array([[1190,   19,    8,    4,    0,    5,    5,    1],
       [   2,  141,   11,    0,    0,    0,    0,    0],
       [  10,    3,   61,    2,    0,    0,    1,    0],
       [   5,    0,    0,  450,    2,    3,    6,    3],
       [   0,    0,    3,    3,   72,    0,    0,    0],
       [   0,    0,    0,    3,    0,   33,    3,    0],
       [   1,    0,    0,    1,    1,    0,   13,    0],
       [   0,    0,    0,    0,    0,    0,    0,   39]], dtype=int64)

In [16]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,6,8,10]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(train.iloc[:,:22],train.iloc[:,24])

GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [4, 6, 8, 10]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [17]:
accuracy_score(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

0.966254752851711

In [18]:
confusion_matrix(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

array([[ 179,    0,   10,    1,    0,    1,    0,    2,    1,    1],
       [   0, 1035,    0,    1,    0,    0,    0,    0,    0,    1],
       [   0,    0,  142,   11,    0,    1,    0,    0,    0,    0],
       [   2,    2,    5,   67,    0,    0,    0,    0,    1,    0],
       [   3,    0,    0,    0,  132,    2,    0,    1,    1,    0],
       [   0,    2,    0,    0,    2,  318,    2,    1,    4,    1],
       [   0,    0,    0,    3,    0,    1,   74,    0,    0,    0],
       [   0,    0,    0,    0,    1,    1,    0,   33,    4,    0],
       [   0,    0,    0,    0,    0,    0,    2,    0,   14,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   39]],
      dtype=int64)

In [19]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,6,8,10]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(train.iloc[:,:22],train.iloc[:,25])

C:\Users\li chen\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [4, 6, 8, 10]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [20]:
accuracy_score(test.iloc[:,25],clf.predict(test.iloc[:,:22]))

0.7827946768060836

In [21]:
confusion_matrix(test.iloc[:,25],clf.predict(test.iloc[:,:22]))

array([[10,  2,  0, ...,  0,  0,  0],
       [ 2, 13,  2, ...,  0,  0,  0],
       [ 0,  0,  4, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  9,  0,  0],
       [ 0,  0,  0, ...,  0,  6,  0],
       [ 0,  0,  0, ...,  0,  0,  5]], dtype=int64)

__SMOTE__

In [22]:
X_resampled_smote, y_resampled_smote = SMOTE().fit_sample(train.iloc[:,:22], train.iloc[:,23])

In [23]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,6,8,10]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(X_resampled_smote,y_resampled_smote)

GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [4, 6, 8, 10]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [24]:
accuracy_score(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

0.9153992395437263

In [25]:
confusion_matrix(test.iloc[:,23],clf.predict(test.iloc[:,:22]))

array([[1119,   29,   29,    4,    0,   10,   37,    4],
       [   2,  144,    8,    0,    0,    0,    0,    0],
       [   5,    3,   67,    2,    0,    0,    0,    0],
       [   5,    0,    0,  436,    2,   11,    9,    6],
       [   0,    0,    3,    1,   74,    0,    0,    0],
       [   0,    0,    0,    3,    0,   34,    2,    0],
       [   1,    0,    0,    1,    1,    0,   13,    0],
       [   0,    0,    0,    0,    0,    0,    0,   39]], dtype=int64)

In [42]:
X_resampled_smote, y_resampled_smote = SMOTE().fit_sample(train.iloc[:,:22], train.iloc[:,24])

In [43]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,8]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(X_resampled_smote,y_resampled_smote)

GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1, param_grid={'C': [4, 8]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [44]:
accuracy_score(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

0.9581749049429658

In [45]:
confusion_matrix(test.iloc[:,24],clf.predict(test.iloc[:,:22]))

array([[ 177,    0,   10,    3,    0,    1,    0,    2,    1,    1],
       [   0, 1031,    0,    2,    1,    0,    0,    0,    0,    3],
       [   1,    0,  139,   12,    0,    1,    0,    0,    0,    1],
       [   3,    2,    3,   67,    0,    1,    0,    0,    1,    0],
       [   1,    0,    0,    0,  132,    2,    1,    1,    2,    0],
       [   0,    4,    0,    0,    5,  311,    2,    3,    4,    1],
       [   0,    1,    0,    3,    0,    0,   74,    0,    0,    0],
       [   0,    0,    0,    0,    2,    1,    0,   34,    2,    0],
       [   0,    0,    0,    0,    0,    0,    4,    0,   12,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   39]],
      dtype=int64)

In [58]:
X_resampled_smote, y_resampled_smote = SMOTE().fit_sample(train.iloc[:,:22], train.iloc[:,22])

In [63]:
y_resampled_smote

array(['Leptodactylidae', 'Leptodactylidae', 'Leptodactylidae', ...,
       'Bufonidae', 'Bufonidae', 'Bufonidae'], dtype=object)

In [59]:
l1svc=LinearSVC(penalty='l1',dual=False,max_iter=1000,class_weight='balanced')
parameters={'C':[4,6,8,10]}
clf=GridSearchCV(l1svc,param_grid=parameters,cv=10)
clf.fit(X_resampled_smote,y_resampled_smote)

GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [4, 6, 8, 10]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [64]:
accuracy_score(test.iloc[:,22],clf.predict(test.iloc[:,:22]))

0.9130228136882129

In [66]:
confusion_matrix(test.iloc[:,22],clf.predict(test.iloc[:,:22]))

array([[  14,    0,    2,    0],
       [   0,  151,    0,    3],
       [  27,   26,  535,   36],
       [  28,   23,   38, 1221]], dtype=int64)

__K-means__

In [36]:
from sklearn.cluster import KMeans
from collections import Counter

In [40]:
for i in df.iloc[:,22:25]:
    for j in range(50):
        print('\n'+i+', '+str(j+1)+' , result:\n')
        kmeans=KMeans(n_clusters=j+1)
        kmeans.fit(df.iloc[:,:22])
        clabel=i+'_cluster'
        df[clabel]=kmeans.labels_
        for k in range(j+1):
            result=Counter(df.loc[df[clabel]==k,i]).most_common(1)[0][0]
            print('cluster '+str(k)+' most common:'+result)


Family, 1 , result:

cluster 0 most common:Leptodactylidae

Family, 2 , result:

cluster 0 most common:Hylidae
cluster 1 most common:Leptodactylidae

Family, 3 , result:

cluster 0 most common:Hylidae
cluster 1 most common:Leptodactylidae
cluster 2 most common:Hylidae

Family, 4 , result:

cluster 0 most common:Hylidae
cluster 1 most common:Leptodactylidae
cluster 2 most common:Hylidae
cluster 3 most common:Dendrobatidae

Family, 5 , result:

cluster 0 most common:Hylidae
cluster 1 most common:Hylidae
cluster 2 most common:Dendrobatidae
cluster 3 most common:Leptodactylidae
cluster 4 most common:Leptodactylidae

Family, 6 , result:

cluster 0 most common:Leptodactylidae
cluster 1 most common:Dendrobatidae
cluster 2 most common:Leptodactylidae
cluster 3 most common:Hylidae
cluster 4 most common:Leptodactylidae
cluster 5 most common:Hylidae

Family, 7 , result:

cluster 0 most common:Leptodactylidae
cluster 1 most common:Leptodactylidae
cluster 2 most common:Hylidae
cluster 3 most commo

cluster 0 most common:Hylidae
cluster 1 most common:Dendrobatidae
cluster 2 most common:Hylidae
cluster 3 most common:Hylidae
cluster 4 most common:Leptodactylidae
cluster 5 most common:Leptodactylidae
cluster 6 most common:Hylidae
cluster 7 most common:Hylidae
cluster 8 most common:Leptodactylidae
cluster 9 most common:Leptodactylidae
cluster 10 most common:Leptodactylidae
cluster 11 most common:Dendrobatidae
cluster 12 most common:Dendrobatidae
cluster 13 most common:Hylidae
cluster 14 most common:Leptodactylidae
cluster 15 most common:Leptodactylidae
cluster 16 most common:Leptodactylidae
cluster 17 most common:Leptodactylidae
cluster 18 most common:Hylidae
cluster 19 most common:Hylidae
cluster 20 most common:Hylidae
cluster 21 most common:Leptodactylidae

Family, 23 , result:

cluster 0 most common:Hylidae
cluster 1 most common:Leptodactylidae
cluster 2 most common:Hylidae
cluster 3 most common:Leptodactylidae
cluster 4 most common:Leptodactylidae
cluster 5 most common:Leptodactyl

cluster 0 most common:Leptodactylidae
cluster 1 most common:Hylidae
cluster 2 most common:Hylidae
cluster 3 most common:Leptodactylidae
cluster 4 most common:Hylidae
cluster 5 most common:Leptodactylidae
cluster 6 most common:Dendrobatidae
cluster 7 most common:Leptodactylidae
cluster 8 most common:Leptodactylidae
cluster 9 most common:Hylidae
cluster 10 most common:Dendrobatidae
cluster 11 most common:Dendrobatidae
cluster 12 most common:Hylidae
cluster 13 most common:Leptodactylidae
cluster 14 most common:Leptodactylidae
cluster 15 most common:Leptodactylidae
cluster 16 most common:Hylidae
cluster 17 most common:Hylidae
cluster 18 most common:Hylidae
cluster 19 most common:Leptodactylidae
cluster 20 most common:Hylidae
cluster 21 most common:Hylidae
cluster 22 most common:Hylidae
cluster 23 most common:Leptodactylidae
cluster 24 most common:Leptodactylidae
cluster 25 most common:Leptodactylidae
cluster 26 most common:Leptodactylidae
cluster 27 most common:Hylidae
cluster 28 most comm

cluster 0 most common:Leptodactylidae
cluster 1 most common:Hylidae
cluster 2 most common:Dendrobatidae
cluster 3 most common:Hylidae
cluster 4 most common:Leptodactylidae
cluster 5 most common:Hylidae
cluster 6 most common:Leptodactylidae
cluster 7 most common:Hylidae
cluster 8 most common:Leptodactylidae
cluster 9 most common:Leptodactylidae
cluster 10 most common:Dendrobatidae
cluster 11 most common:Hylidae
cluster 12 most common:Leptodactylidae
cluster 13 most common:Leptodactylidae
cluster 14 most common:Leptodactylidae
cluster 15 most common:Leptodactylidae
cluster 16 most common:Hylidae
cluster 17 most common:Leptodactylidae
cluster 18 most common:Hylidae
cluster 19 most common:Hylidae
cluster 20 most common:Leptodactylidae
cluster 21 most common:Dendrobatidae
cluster 22 most common:Hylidae
cluster 23 most common:Hylidae
cluster 24 most common:Leptodactylidae
cluster 25 most common:Leptodactylidae
cluster 26 most common:Hylidae
cluster 27 most common:Leptodactylidae
cluster 28 m

cluster 0 most common:Leptodactylidae
cluster 1 most common:Hylidae
cluster 2 most common:Hylidae
cluster 3 most common:Leptodactylidae
cluster 4 most common:Leptodactylidae
cluster 5 most common:Leptodactylidae
cluster 6 most common:Leptodactylidae
cluster 7 most common:Dendrobatidae
cluster 8 most common:Hylidae
cluster 9 most common:Hylidae
cluster 10 most common:Leptodactylidae
cluster 11 most common:Dendrobatidae
cluster 12 most common:Leptodactylidae
cluster 13 most common:Leptodactylidae
cluster 14 most common:Hylidae
cluster 15 most common:Leptodactylidae
cluster 16 most common:Leptodactylidae
cluster 17 most common:Hylidae
cluster 18 most common:Dendrobatidae
cluster 19 most common:Leptodactylidae
cluster 20 most common:Hylidae
cluster 21 most common:Leptodactylidae
cluster 22 most common:Hylidae
cluster 23 most common:Dendrobatidae
cluster 24 most common:Hylidae
cluster 25 most common:Leptodactylidae
cluster 26 most common:Hylidae
cluster 27 most common:Hylidae
cluster 28 mos

cluster 0 most common:Leptodactylidae
cluster 1 most common:Bufonidae
cluster 2 most common:Leptodactylidae
cluster 3 most common:Dendrobatidae
cluster 4 most common:Hylidae
cluster 5 most common:Hylidae
cluster 6 most common:Leptodactylidae
cluster 7 most common:Hylidae
cluster 8 most common:Leptodactylidae
cluster 9 most common:Hylidae
cluster 10 most common:Leptodactylidae
cluster 11 most common:Leptodactylidae
cluster 12 most common:Hylidae
cluster 13 most common:Hylidae
cluster 14 most common:Leptodactylidae
cluster 15 most common:Leptodactylidae
cluster 16 most common:Hylidae
cluster 17 most common:Dendrobatidae
cluster 18 most common:Hylidae
cluster 19 most common:Hylidae
cluster 20 most common:Leptodactylidae
cluster 21 most common:Hylidae
cluster 22 most common:Hylidae
cluster 23 most common:Leptodactylidae
cluster 24 most common:Leptodactylidae
cluster 25 most common:Dendrobatidae
cluster 26 most common:Leptodactylidae
cluster 27 most common:Leptodactylidae
cluster 28 most co

cluster 0 most common:Adenomera
cluster 1 most common:Adenomera
cluster 2 most common:Ameerega
cluster 3 most common:Hypsiboas
cluster 4 most common:Hypsiboas
cluster 5 most common:Hypsiboas
cluster 6 most common:Adenomera
cluster 7 most common:Adenomera
cluster 8 most common:Adenomera
cluster 9 most common:Adenomera
cluster 10 most common:Leptodactylus
cluster 11 most common:Ameerega
cluster 12 most common:Ameerega
cluster 13 most common:Adenomera
cluster 14 most common:Hypsiboas
cluster 15 most common:Scinax
cluster 16 most common:Dendropsophus

Genus, 18 , result:

cluster 0 most common:Adenomera
cluster 1 most common:Dendropsophus
cluster 2 most common:Hypsiboas
cluster 3 most common:Adenomera
cluster 4 most common:Adenomera
cluster 5 most common:Ameerega
cluster 6 most common:Hypsiboas
cluster 7 most common:Adenomera
cluster 8 most common:Hypsiboas
cluster 9 most common:Adenomera
cluster 10 most common:Ameerega
cluster 11 most common:Hypsiboas
cluster 12 most common:Hypsiboas
clus

cluster 0 most common:Adenomera
cluster 1 most common:Dendropsophus
cluster 2 most common:Hypsiboas
cluster 3 most common:Adenomera
cluster 4 most common:Adenomera
cluster 5 most common:Hypsiboas
cluster 6 most common:Adenomera
cluster 7 most common:Rhinella
cluster 8 most common:Ameerega
cluster 9 most common:Hypsiboas
cluster 10 most common:Hypsiboas
cluster 11 most common:Leptodactylus
cluster 12 most common:Adenomera
cluster 13 most common:Scinax
cluster 14 most common:Ameerega
cluster 15 most common:Hypsiboas
cluster 16 most common:Dendropsophus
cluster 17 most common:Hypsiboas
cluster 18 most common:Ameerega
cluster 19 most common:Adenomera
cluster 20 most common:Ameerega
cluster 21 most common:Adenomera
cluster 22 most common:Adenomera
cluster 23 most common:Adenomera
cluster 24 most common:Hypsiboas
cluster 25 most common:Adenomera
cluster 26 most common:Adenomera
cluster 27 most common:Scinax
cluster 28 most common:Leptodactylus

Genus, 30 , result:

cluster 0 most common:Aden

cluster 0 most common:Adenomera
cluster 1 most common:Scinax
cluster 2 most common:Adenomera
cluster 3 most common:Hypsiboas
cluster 4 most common:Adenomera
cluster 5 most common:Adenomera
cluster 6 most common:Rhinella
cluster 7 most common:Dendropsophus
cluster 8 most common:Adenomera
cluster 9 most common:Hypsiboas
cluster 10 most common:Hypsiboas
cluster 11 most common:Adenomera
cluster 12 most common:Ameerega
cluster 13 most common:Osteocephalus
cluster 14 most common:Adenomera
cluster 15 most common:Hypsiboas
cluster 16 most common:Scinax
cluster 17 most common:Leptodactylus
cluster 18 most common:Adenomera
cluster 19 most common:Ameerega
cluster 20 most common:Hypsiboas
cluster 21 most common:Adenomera
cluster 22 most common:Adenomera
cluster 23 most common:Adenomera
cluster 24 most common:Dendropsophus
cluster 25 most common:Hypsiboas
cluster 26 most common:Ameerega
cluster 27 most common:Hypsiboas
cluster 28 most common:Hypsiboas
cluster 29 most common:Leptodactylus
cluster 30

cluster 0 most common:Adenomera
cluster 1 most common:Hypsiboas
cluster 2 most common:Hypsiboas
cluster 3 most common:Ameerega
cluster 4 most common:Hypsiboas
cluster 5 most common:Hypsiboas
cluster 6 most common:Adenomera
cluster 7 most common:Adenomera
cluster 8 most common:Adenomera
cluster 9 most common:Scinax
cluster 10 most common:Leptodactylus
cluster 11 most common:Ameerega
cluster 12 most common:Adenomera
cluster 13 most common:Hypsiboas
cluster 14 most common:Ameerega
cluster 15 most common:Adenomera
cluster 16 most common:Osteocephalus
cluster 17 most common:Hypsiboas
cluster 18 most common:Adenomera
cluster 19 most common:Dendropsophus
cluster 20 most common:Adenomera
cluster 21 most common:Scinax
cluster 22 most common:Dendropsophus
cluster 23 most common:Adenomera
cluster 24 most common:Adenomera
cluster 25 most common:Hypsiboas
cluster 26 most common:Ameerega
cluster 27 most common:Rhinella
cluster 28 most common:Adenomera
cluster 29 most common:Adenomera
cluster 30 most

cluster 0 most common:Hypsiboas
cluster 1 most common:Adenomera
cluster 2 most common:Adenomera
cluster 3 most common:Hypsiboas
cluster 4 most common:Adenomera
cluster 5 most common:Adenomera
cluster 6 most common:Ameerega
cluster 7 most common:Hypsiboas
cluster 8 most common:Adenomera
cluster 9 most common:Osteocephalus
cluster 10 most common:Adenomera
cluster 11 most common:Ameerega
cluster 12 most common:Ameerega
cluster 13 most common:Adenomera
cluster 14 most common:Ameerega
cluster 15 most common:Adenomera
cluster 16 most common:Scinax
cluster 17 most common:Adenomera
cluster 18 most common:Hypsiboas
cluster 19 most common:Dendropsophus
cluster 20 most common:Adenomera
cluster 21 most common:Hypsiboas
cluster 22 most common:Rhinella
cluster 23 most common:Dendropsophus
cluster 24 most common:Adenomera
cluster 25 most common:Leptodactylus
cluster 26 most common:Adenomera
cluster 27 most common:Hypsiboas
cluster 28 most common:Ameerega
cluster 29 most common:Leptodactylus
cluster 3

cluster 0 most common:AdenomeraHylaedactylus
cluster 1 most common:AdenomeraAndre
cluster 2 most common:Ameeregatrivittata
cluster 3 most common:HypsiboasCordobae
cluster 4 most common:AdenomeraHylaedactylus
cluster 5 most common:Ameeregatrivittata
cluster 6 most common:AdenomeraHylaedactylus
cluster 7 most common:LeptodactylusFuscus
cluster 8 most common:AdenomeraAndre
cluster 9 most common:ScinaxRuber
cluster 10 most common:HypsiboasCinerascens
cluster 11 most common:Ameeregatrivittata
cluster 12 most common:HypsiboasCordobae
cluster 13 most common:AdenomeraHylaedactylus
cluster 14 most common:HypsiboasCordobae
cluster 15 most common:HylaMinuta
cluster 16 most common:AdenomeraAndre
cluster 17 most common:HypsiboasCinerascens

Species, 19 , result:

cluster 0 most common:HypsiboasCordobae
cluster 1 most common:AdenomeraHylaedactylus
cluster 2 most common:AdenomeraHylaedactylus
cluster 3 most common:Ameeregatrivittata
cluster 4 most common:HypsiboasCinerascens
cluster 5 most common:Hyl

cluster 0 most common:AdenomeraHylaedactylus
cluster 1 most common:HypsiboasCordobae
cluster 2 most common:HypsiboasCinerascens
cluster 3 most common:AdenomeraAndre
cluster 4 most common:Ameeregatrivittata
cluster 5 most common:AdenomeraAndre
cluster 6 most common:AdenomeraHylaedactylus
cluster 7 most common:AdenomeraHylaedactylus
cluster 8 most common:AdenomeraHylaedactylus
cluster 9 most common:AdenomeraHylaedactylus
cluster 10 most common:HypsiboasCinerascens
cluster 11 most common:OsteocephalusOophagus
cluster 12 most common:Ameeregatrivittata
cluster 13 most common:HylaMinuta
cluster 14 most common:AdenomeraHylaedactylus
cluster 15 most common:HylaMinuta
cluster 16 most common:AdenomeraAndre
cluster 17 most common:LeptodactylusFuscus
cluster 18 most common:ScinaxRuber
cluster 19 most common:HypsiboasCordobae
cluster 20 most common:AdenomeraHylaedactylus
cluster 21 most common:AdenomeraHylaedactylus
cluster 22 most common:Ameeregatrivittata
cluster 23 most common:Ameeregatrivittata

cluster 0 most common:AdenomeraHylaedactylus
cluster 1 most common:Rhinellagranulosa
cluster 2 most common:HypsiboasCinerascens
cluster 3 most common:AdenomeraHylaedactylus
cluster 4 most common:HylaMinuta
cluster 5 most common:AdenomeraHylaedactylus
cluster 6 most common:AdenomeraAndre
cluster 7 most common:LeptodactylusFuscus
cluster 8 most common:Ameeregatrivittata
cluster 9 most common:HypsiboasCordobae
cluster 10 most common:AdenomeraHylaedactylus
cluster 11 most common:HypsiboasCinerascens
cluster 12 most common:Ameeregatrivittata
cluster 13 most common:Ameeregatrivittata
cluster 14 most common:AdenomeraAndre
cluster 15 most common:HypsiboasCinerascens
cluster 16 most common:Ameeregatrivittata
cluster 17 most common:AdenomeraHylaedactylus
cluster 18 most common:AdenomeraHylaedactylus
cluster 19 most common:AdenomeraHylaedactylus
cluster 20 most common:Ameeregatrivittata
cluster 21 most common:AdenomeraAndre
cluster 22 most common:ScinaxRuber
cluster 23 most common:AdenomeraHylaed

cluster 0 most common:HypsiboasCinerascens
cluster 1 most common:AdenomeraHylaedactylus
cluster 2 most common:Ameeregatrivittata
cluster 3 most common:Rhinellagranulosa
cluster 4 most common:AdenomeraHylaedactylus
cluster 5 most common:HylaMinuta
cluster 6 most common:LeptodactylusFuscus
cluster 7 most common:AdenomeraHylaedactylus
cluster 8 most common:HypsiboasCordobae
cluster 9 most common:AdenomeraAndre
cluster 10 most common:Ameeregatrivittata
cluster 11 most common:AdenomeraHylaedactylus
cluster 12 most common:AdenomeraAndre
cluster 13 most common:Ameeregatrivittata
cluster 14 most common:AdenomeraAndre
cluster 15 most common:HypsiboasCinerascens
cluster 16 most common:AdenomeraHylaedactylus
cluster 17 most common:ScinaxRuber
cluster 18 most common:HypsiboasCinerascens
cluster 19 most common:AdenomeraHylaedactylus
cluster 20 most common:HylaMinuta
cluster 21 most common:AdenomeraAndre
cluster 22 most common:Ameeregatrivittata
cluster 23 most common:AdenomeraHylaedactylus
cluster 

cluster 0 most common:AdenomeraHylaedactylus
cluster 1 most common:HylaMinuta
cluster 2 most common:HypsiboasCordobae
cluster 3 most common:HypsiboasCinerascens
cluster 4 most common:AdenomeraAndre
cluster 5 most common:AdenomeraHylaedactylus
cluster 6 most common:AdenomeraHylaedactylus
cluster 7 most common:Ameeregatrivittata
cluster 8 most common:LeptodactylusFuscus
cluster 9 most common:Ameeregatrivittata
cluster 10 most common:Ameeregatrivittata
cluster 11 most common:AdenomeraAndre
cluster 12 most common:HypsiboasCordobae
cluster 13 most common:AdenomeraHylaedactylus
cluster 14 most common:LeptodactylusFuscus
cluster 15 most common:ScinaxRuber
cluster 16 most common:AdenomeraHylaedactylus
cluster 17 most common:Ameeregatrivittata
cluster 18 most common:AdenomeraHylaedactylus
cluster 19 most common:HypsiboasCinerascens
cluster 20 most common:LeptodactylusFuscus
cluster 21 most common:HypsiboasCordobae
cluster 22 most common:AdenomeraHylaedactylus
cluster 23 most common:ScinaxRuber


cluster 0 most common:HypsiboasCordobae
cluster 1 most common:AdenomeraHylaedactylus
cluster 2 most common:AdenomeraAndre
cluster 3 most common:HypsiboasCinerascens
cluster 4 most common:Ameeregatrivittata
cluster 5 most common:AdenomeraHylaedactylus
cluster 6 most common:AdenomeraAndre
cluster 7 most common:Ameeregatrivittata
cluster 8 most common:OsteocephalusOophagus
cluster 9 most common:AdenomeraHylaedactylus
cluster 10 most common:LeptodactylusFuscus
cluster 11 most common:HypsiboasCordobae
cluster 12 most common:Ameeregatrivittata
cluster 13 most common:HylaMinuta
cluster 14 most common:LeptodactylusFuscus
cluster 15 most common:HylaMinuta
cluster 16 most common:AdenomeraHylaedactylus
cluster 17 most common:HylaMinuta
cluster 18 most common:AdenomeraHylaedactylus
cluster 19 most common:HypsiboasCordobae
cluster 20 most common:AdenomeraAndre
cluster 21 most common:HypsiboasCinerascens
cluster 22 most common:AdenomeraHylaedactylus
cluster 23 most common:ScinaxRuber
cluster 24 most

In [39]:
Hamm=pd.DataFrame()
for j in range(50):
    for i in df.iloc[:,22:25]:
        kmeans=KMeans(n_clusters=j+1)
        kmeans.fit(df.iloc[:,:22])
        clabel=i+'_cluster'
        df[clabel]=kmeans.labels_
        arr_clus='K_'+i
        for k in range(j+1):
            result=Counter(df.loc[df[clabel]==k,i]).most_common(1)[0][0]
            df.loc[df[clabel]==k,arr_clus]=result
    df['Hamming_distance']=(df['Family']!=df['K_Family']).astype('int')+(df['Genus']!=df['K_Genus']).astype('int')+(df['Species']!=df['K_Species']).astype('int')
    Hamm.loc[j,'avg_distance']=np.mean(df['Hamming_distance'])
    Hamm.loc[j,'Hamm_loss']=np.sum(df['Hamming_distance'])/(3*len(df))
    Hamm.loc[j,'Hamm_score']=np.sum((3-df['Hamming_distance'])/(3+df['Hamming_distance']))/len(df)

In [41]:
Hamm

avg_distance  Hamm_loss  Hamm_score
0       1.325504   0.441835    0.537596
1       0.894232   0.298077    0.681779
2       0.893259   0.297753    0.681862
3       0.657262   0.219087    0.773912
4       0.498541   0.166180    0.826671
5       0.499236   0.166412    0.826518
6       0.558026   0.186009    0.807783
7       0.490063   0.163354    0.820403
8       0.407783   0.135928    0.845434
9       0.347186   0.115729    0.868826
10      0.334121   0.111374    0.873537
11      0.345379   0.115126    0.869215
12      0.308270   0.102757    0.888464
13      0.309798   0.103266    0.883905
14      0.307019   0.102340    0.882293
15      0.282557   0.094186    0.888423
16      0.271161   0.090387    0.895052
17      0.255733   0.085244    0.901015
18      0.235858   0.078619    0.908061
19      0.201807   0.067269    0.922766
20      0.229604   0.076535    0.910090
21      0.192356   0.064119    0.927561
22      0.199027   0.066342    0.926657
23      0.167338   0.055779    0.936734
24      0.194580   0.064860    0.927755
25      0.161779   0.053926    0.942085
26      0.183044   0.061015    0.933690
27      0.166921   0.055640    0.936581
28      0.174427   0.058142    0.934093
29      0.161084   0.053695    0.937915
30      0.174566   0.058189    0.933607
31      0.162335   0.054112    0.934496
32      0.162335   0.054112    0.937192
33      0.158582   0.052861    0.939736
34      0.157470   0.052490    0.940028
35      0.158999   0.053000    0.938707
36      0.159833   0.053278    0.941682
37      0.159694   0.053231    0.939931
38      0.154969   0.051656    0.939305
39      0.156220   0.052073    0.941306
40      0.144267   0.048089    0.943280
41      0.151772   0.050591    0.939569
42      0.150382   0.050127    0.942585
43      0.144823   0.048274    0.944142
44      0.151911   0.050637    0.940695
45      0.148019   0.049340    0.941932
46      0.139541   0.046514    0.945851
47      0.144545   0.048182    0.941682
48      0.130785   0.043595    0.949993
49      0.138429   0.046143    0.946393